STATE_START = "START"
STATE_MAIN_MENU = "MAIN_MENU"
STATE_CATALOGUE = "CATALOGUE"
STATE_FAQ_MENU = "FAQ_MENU"
STATE_AI_FAQ = "AI_FAQ"
STATE_AGENT = "AGENT"

STATE_SERVICES = "SERVICES"
STATE_LOAN_TYPES = "LOAN_TYPES"
STATE_CONFIRM_APPLY = "CONFIRM_APPLY"

STATE_GET_NAME = "GET_NAME"
STATE_GET_AGE = "GET_AGE"
STATE_GET_ADDRESS = "GET_ADDRESS"
STATE_GET_ID = "GET_ID"
STATE_GET_ID_PHOTO = "GET_ID_PHOTO"
STATE_GET_AMOUNT = "GET_AMOUNT"
STATE_FINAL_CONFIRM = "FINAL_CONFIRM"

